### ISSUE TITLE
Guacamole SSH Issue

### ISSUE THREAD

**Issue by chiragnahata** [jwetzell/docker-guacamole#8] opened 2022-10-11 16:45 UTC
Issue with guacamole please help as soon as possible

Unable to connect to ssh using guacamole. I am getting this error. Is this becuase my server asks fro fingerprint verification or any other reason

![image](https://user-images.githubusercontent.com/63905783/195151114-53f192a8-788b-425a-bd1f-0d174c3743f5.png)

docker run \
  -p 4822:8080 \
  -v /Portainer/AppData/Guacamole/Config:/config \
  jwetzell/guacamole:arm32v7

**Comment by ovizii** [comment] 2022-10-17 10:40
Are you connecting via ssh (as your thread title indicates) or via RDP (as the screenshot indicates)?

Although I'd like to add that the screenshot indicates that the remote desktop server encountered the error NOT guacamole so why not go check your remote desktop server's logs?

**Comment by jwetzell** [comment] 2022-10-20 18:08
Anything in logs?

**Comment by chiragnahata** [comment] 2022-10-21 06:13
> Are you connecting via ssh (as your thread title indicates) or via RDP (as the screenshot indicates)?
> 
> Also I'd like to add that the screenshot indicates that the remote desktop server encountered the error NOT guacamole so why not go check your remote desktop server's logs?

I am doing a ssh connection

**Comment by chiragnahata** [comment] 2022-10-21 06:13
> Anything in logs?

No nothing I am able to do a ssh connection using Termius also but not through guacamole

**Comment by chiragnahata** [comment] 2022-10-21 06:14
https://www.reddit.com/r/selfhosted/comments/y6v4g8/guacamole_ssh_error/ - Check out this

**Comment by chiragnahata** [comment] 2022-10-21 06:15
> https://www.reddit.com/r/selfhosted/comments/y6v4g8/guacamole_ssh_error/ - Check out this

Someone in reddit said me : 

Guacamole doesn't support the new certificate format from OpenSSH, it needs to be converted to an older format. Something like this:

ssh-keygen -m pem -f <certificate>

Make sure to make a copy of the <certificate> first, as this command will overwrite it.

Me: 

After using the command and converting it into rsa private key also same error

**Comment by chiragnahata** [comment] 2022-10-29 05:11
Please help not resolved yet

**Comment by jwetzell** [comment] 2022-10-31 16:19
Could possible be [this](https://www.reddit.com/r/linuxquestions/comments/ued2vq/apache_guacamole_cant_ssh_into_ubuntu_2204/). I ran into this when I upgraded things to Ubuntu 22.04

**Comment by chiragnahata** [comment] 2022-11-01 04:55
> Could possibly be [this](https://www.reddit.com/r/linuxquestions/comments/ued2vq/apache_guacamole_cant_ssh_into_ubuntu_2204/). I ran into this when I upgraded things to Ubuntu 22.04

Tried but still cannot access via guacamole. And also it stopped the ssh connection from outside my network. Guacamole is deployed on my cloud on my local network

**Comment by ckwcfm** [comment] 2023-08-28 12:08
I got this error too. It only have to me when I try to login using private key.

**Comment by indigodelta** [comment] 2023-10-11 10:04
I have this problem too.  I am using a password with ssh.  I can log in directly to the server using an ssh terminal but not through guacamole.  I made the change in the linked Reddit post and it solved the problem.  I found [this link](https://issues.apache.org/jira/browse/GUACAMOLE-1504) which suggests that this has been fixed in 1.5.0 of guacamole, but I am using the latest one from this distribution and the problem is still there.  Does this distribution not have the latest guacamole build or is it a bug in guacamole?

**Comment by jwetzell** [comment] 2023-10-11 11:01
I have been unable to find a way to upgrade the version of libssh2 in the image. I believe bringing that up to date would resolve the SSH related problems.

**Comment by indigodelta** [comment] 2023-10-11 11:08
> I have been unable to find a way to upgrade the version of libssh2 in the image. I believe bringing that up to date would resolve the SSH related problems.

That explains the problem.  Thanks for the clarification.

**Comment by jwetzell** [comment] 2023-12-19 20:32
The `1.5.4-am64`/`latest` and `1.5.4-arm64`/`arm64` images have been updated to included the latest `libssh2` version which should fix this issue.  If the problem still exists please reopen the issue.

**Closed by jwetzell** 2023-12-19 20:32 UTC
